### ISSUE TITLE
send button problem

### ISSUE THREAD

**Issue by aizaz319** [three-star-programmer/Mail-sendind-form#1]
https://github.com/three-star-programmer/Mail-sendind-form/commit/21ac80a05888fe18c58b7dde089eb0b35f3da415#r33312063

hi giys we have a problem in email sending, email is going without attachments but if i select attachments it it is not sending with attachments.

**Comment by aizaz319** [comment]
https://github.com/three-star-programmer/Mail-sendind-form/commit/f023120ec7133392fdf3766f9706f17aa4ce6569#r33312171

attachment button is not working properly

**Comment by samiashariff1994** [comment]
i will try to research about the problem

**Comment by aizaz319** [comment]
ok

**Comment by janahajj** [comment]
okay me too
